"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Carpeta con los datos que NO son código: base de datos, fotos subidas y archivos estáticos recopilados.
# En tu computadora es la misma carpeta del proyecto; en el servidor se define con DATA_DIR para que
# actualizar el código nunca toque los datos.
DATA_DIR = Path(os.getenv('DATA_DIR', BASE_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dr@^h@$x^yln5%+w19bv1yk%kha3dg!d@8t%a#&&5igx+x5$$l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'   # por defecto apagado: hay que prenderlo a propósito en desarrollo

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('Con DEBUG apagado hace falta definir una SECRET_KEY propia en el archivo .env')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Detrás de nginx: se confía en el aviso de nginx de que el pedido original era HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Con HTTPS activo (USAR_HTTPS=True) las cookies solo viajan cifradas
if os.getenv('USAR_HTTPS', 'False') == 'True':
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Número de WhatsApp para el botón de contacto directo (formato: código de país + número, sin +, sin espacios)
WHATSAPP_NUMBER = os.getenv('WHATSAPP_NUMBER', '5491133405963')

# Clave de la API de Gemini (Google AI), para generar descripciones de propiedades con IA
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'unfold',                 # tema moderno del panel de administración (debe ir antes que admin)
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Añadido para manejo de estáticos
    'django.contrib.sitemaps',
    'propiedades',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'propiedades.context_processors.whatsapp',
                'propiedades.context_processors.seguimiento',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application' # Añadido por si acaso falta


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LOCALE_PATHS = [BASE_DIR / 'locale']
LANGUAGE_CODE = 'es-ar' # Cambiado a español de Argentina
TIME_ZONE = 'America/Argentina/Buenos_Aires' # Cambiado a tu zona horaria
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# La URL que se usará para referirse a los archivos estáticos
STATIC_URL = 'static/'

# La carpeta donde Django buscará tus archivos estáticos (nuestra carpeta 'static')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Archivos subidos por los usuarios (fotos de propiedades)
MEDIA_URL = 'media/'
MEDIA_ROOT = DATA_DIR / 'media'

# Donde `collectstatic` junta los archivos estáticos para que nginx los sirva en producción
STATIC_ROOT = DATA_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURACIÓN DE EMAIL PARA PRODUCCIÓN (GMAIL) ---
# Todo se configura desde el archivo .env (ver .env.example). Sirve para Gmail, Google Workspace o el
# correo del hosting del dominio: solo cambian EMAIL_HOST, EMAIL_PORT y si se usa TLS o SSL.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'   # puerto 465
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True' and not EMAIL_USE_SSL   # puerto 587
EMAIL_TIMEOUT = 15
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')          # casilla desde la que se envía
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # su contraseña (o contraseña de aplicación)

# Desde qué nombre/casilla salen los mails
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or (
    f'David Rodríguez Propiedades <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else None
)

# A dónde llegan las consultas de los formularios (puede ser distinta de la casilla que envía)
EMAIL_DESTINO_CONSULTAS = os.getenv('EMAIL_DESTINO_CONSULTAS', 'info@davidrodriguezprop.com')


# --- PANEL DE ADMINISTRACIÓN (tema django-unfold) ---
from django.templatetags.static import static  # noqa: E402
from django.urls import reverse_lazy  # noqa: E402

from propiedades.utils import static_versionado  # noqa: E402

UNFOLD = {
    "SITE_TITLE": "David Rodríguez Propiedades",
    "SITE_HEADER": "David Rodríguez Propiedades",
    "SITE_SUBHEADER": "Panel de administración",
    "SITE_URL": "/",
    "SITE_SYMBOL": "apartment",
    "SITE_LOGO": lambda request: static("img/logo.png"),
    "SITE_FAVICONS": [
        {"rel": "icon", "sizes": "32x32", "type": "image/png", "href": lambda request: static("img/logo.png")},
    ],
    "THEME": "dark",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [lambda request: static_versionado("css/admin_panel.css")],
    "COLORS": {
        # Grises neutros (sin tinte azul) para que combine con el negro de la marca
        "base": {
            "50": "oklch(98.5% 0 0)", "100": "oklch(97% 0 0)", "200": "oklch(92.2% 0 0)",
            "300": "oklch(87% 0 0)", "400": "oklch(70.8% 0 0)", "500": "oklch(55.6% 0 0)",
            "600": "oklch(43.9% 0 0)", "700": "oklch(37.1% 0 0)", "800": "oklch(26.9% 0 0)",
            "900": "oklch(20.5% 0 0)", "950": "oklch(14.5% 0 0)",
        },
        # Rojo de la marca como color principal
        "primary": {
            "50": "oklch(97.1% .013 17.38)", "100": "oklch(93.6% .032 17.717)", "200": "oklch(88.5% .062 18.334)",
            "300": "oklch(80.8% .114 19.571)", "400": "oklch(70.4% .191 22.216)", "500": "oklch(63.7% .237 25.331)",
            "600": "oklch(57.7% .245 27.325)", "700": "oklch(50.5% .213 27.518)", "800": "oklch(44.4% .177 26.899)",
            "900": "oklch(39.6% .141 25.723)", "950": "oklch(25.8% .092 26.042)",
        },
    },
    "DASHBOARD_CALLBACK": "propiedades.panel_admin.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Panel",
                "separator": False,
                "items": [
                    {"title": "Inicio", "icon": "dashboard", "link": reverse_lazy("admin:index")},
                ],
            },
            {
                "title": "Propiedades",
                "separator": True,
                "items": [
                    {"title": "Todas las propiedades", "icon": "home_work", "link": reverse_lazy("admin:propiedades_propiedad_changelist")},
                    {"title": "Agregar / importar desde link", "icon": "add_link", "link": reverse_lazy("admin:propiedades_propiedad_add")},
                ],
            },
            {
                "title": "Contactos",
                "separator": True,
                "items": [
                    {"title": "Interesados", "icon": "groups", "link": reverse_lazy("admin:propiedades_interesado_changelist")},
                    {
                        "title": "Pedidos de tasación", "icon": "request_quote",
                        "link": reverse_lazy("admin:propiedades_solicitudtasacion_changelist"),
                        "badge": "propiedades.panel_admin.tasaciones_pendientes",
                        "badge_variant": "danger",
                    },
                    {
                        "title": "Consultas por propiedad", "icon": "mail",
                        "link": reverse_lazy("admin:propiedades_consultapropiedad_changelist"),
                        "badge": "propiedades.panel_admin.consultas_pendientes",
                        "badge_variant": "danger",
                    },
                ],
            },
            {
                "title": "Contenido de la web",
                "separator": True,
                "items": [
                    {"title": "Testimonios", "icon": "format_quote", "link": reverse_lazy("admin:propiedades_testimonio_changelist")},
                    {"title": "Equipo", "icon": "badge", "link": reverse_lazy("admin:propiedades_miembroequipo_changelist")},
                ],
            },
            {
                "title": "Configuración",
                "separator": True,
                "items": [
                    {"title": "Descripciones con IA", "icon": "auto_awesome", "link": reverse_lazy("admin:propiedades_configuracionia_changelist")},
                    {"title": "Datos del sitio", "icon": "tune", "link": reverse_lazy("admin:propiedades_configuracionsitio_changelist")},
                    {"title": "Usuarios", "icon": "person", "link": reverse_lazy("admin:auth_user_changelist")},
                ],
            },
        ],
    },
}
