# Generated by Django 5.2.7 on 2025-10-08 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('dormitorios', models.IntegerField(default=1, verbose_name='Dormitorios')),
                ('metros_cuadrados', models.IntegerField(default=0, verbose_name='M² Construidos')),
                ('banos', models.IntegerField(default=1, verbose_name='Baños')),
                ('tipo_propiedad', models.CharField(choices=[('Casa', 'Casa'), ('Depto', 'Departamento'), ('Local', 'Local Comercial')], default='Casa', max_length=50, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('Venta', 'En Venta'), ('Alq', 'En Alquiler')], default='Venta', max_length=50, verbose_name='Estado')),
                ('esta_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
