# Generated by Django 5.2.7 on 2025-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='amenidades',
            field=models.TextField(blank=True, default='', verbose_name='Amenidades (separadas por coma)'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Propiedad Destacada (Rojo en UI)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('Venta', 'En Venta'), ('Alquiler', 'En Alquiler')], default='Venta', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Depto', 'Departamento'), ('Local', 'Local Comercial'), ('Terreno', 'Terreno')], default='Casa', max_length=50, verbose_name='Tipo'),
        ),
    ]
