# Generated by Django 5.0.7 on 2026-09-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_amenidades_propiedad_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('Venta', 'En Venta'), ('Alquiler', 'En Alquiler'), ('Permuta', 'Permuta')], default='Venta', max_length=50, verbose_name='Estado'),
        ),
    ]
