# Generated by Django 5.0.7 on 2026-09-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_imagen_alter_propiedad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='video_url',
            field=models.URLField(blank=True, help_text="Pegá el link del video (recomendado: subirlo a YouTube como 'Oculto' y pegar ese link acá).", null=True, verbose_name='Video (link de YouTube o Vimeo)'),
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/', verbose_name='Foto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Foto de la galería',
                'verbose_name_plural': 'Fotos de la galería',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
