# Generated by Django 5.0.7 on 2026-09-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_video_url_fotopropiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='URL amigable'),
        ),
        migrations.CreateModel(
            name='ConsultaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Consulta por propiedad',
                'verbose_name_plural': 'Consultas por propiedad',
                'ordering': ['-fecha'],
            },
        ),
    ]
