# Generated by Django 5.0.7 on 2026-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_slug_consultapropiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones_estilo', models.TextField(blank=True, default='No repitas el precio salvo que aporte a la narrativa. Terminá con una frase que invite a imaginarse viviendo ahí o a dar el siguiente paso, sin sonar a cliché publicitario.', help_text="Ej: 'Somos una inmobiliaria familiar con 20 años en Morón, mencionalo cuando quede natural. Tono cercano, sin tecnicismos. Evitá la palabra oportunidad.' Esto se suma a las reglas fijas (nunca inventar datos, longitud corta): no las reemplaza.", verbose_name='Instrucciones de estilo para la IA')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuración de IA',
            },
        ),
    ]
