# Generated by Django 5.0.7 on 2026-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_configuracionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('Venta', 'En Venta'), ('Alquiler', 'En Alquiler'), ('Permuta', 'Permuta'), ('Emprendimiento', 'Emprendimientos')], default='Venta', max_length=50, verbose_name='Estado'),
        ),
    ]
