# Generated by Django 5.0.7 on 2026-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_alter_propiedad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadistica_1_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estadística 1: número')),
                ('estadistica_1_etiqueta', models.CharField(blank=True, default='', max_length=60, verbose_name='Estadística 1: etiqueta')),
                ('estadistica_2_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estadística 2: número')),
                ('estadistica_2_etiqueta', models.CharField(blank=True, default='', max_length=60, verbose_name='Estadística 2: etiqueta')),
                ('estadistica_3_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estadística 3: número')),
                ('estadistica_3_etiqueta', models.CharField(blank=True, default='', max_length=60, verbose_name='Estadística 3: etiqueta')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
