# Generated by Django 5.0.7 on 2026-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_configuracionsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ambientes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Se usa para buscar alquileres por ambientes.', null=True, verbose_name='Ambientes'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD (dólares)'), ('ARS', '$ (pesos)')], default='USD', help_text='Los alquileres suelen publicarse en pesos; las ventas, en dólares.', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
