# Generated by Django 5.0.7 on 2026-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_moneda_ambientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='acepta_permuta',
            field=models.BooleanField(default=False, verbose_name='Acepta permuta'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='apto_credito',
            field=models.BooleanField(default=False, verbose_name='Apto crédito'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='reservado',
            field=models.BooleanField(default=False, help_text="Muestra una banda 'RESERVADA' sobre la foto.", verbose_name='Reservado'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='vendido',
            field=models.BooleanField(default=False, help_text="Muestra una banda 'VENDIDA' sobre la foto. Si querés que deje de aparecer en la web, desmarcá 'Disponible'.", verbose_name='Vendido'),
        ),
    ]
