# Generated by Django 5.0.7 on 2026-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0010_etiquetas_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='link_origen',
            field=models.URLField(blank=True, help_text='Se completa solo cuando la propiedad se importa desde un link. Evita importarla dos veces.', max_length=500, verbose_name='Link de origen'),
        ),
    ]
