# Generated by Django 5.0.7 on 2026-09-21 16:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_link_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtros', models.JSONField(default=dict, verbose_name='Filtros')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Búsqueda')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Último aviso enviado')),
            ],
            options={
                'verbose_name': 'Alerta de búsqueda',
                'verbose_name_plural': 'Alertas de búsqueda',
            },
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('origen', models.CharField(choices=[('favorito', 'Guardó una propiedad'), ('alerta', 'Pidió alertas de búsqueda'), ('popup', 'Ventana de novedades'), ('consulta', 'Consulta por una propiedad'), ('contacto', 'Formulario de contacto')], default='popup', max_length=20, verbose_name='Cómo llegó')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('acepta_novedades', models.BooleanField(default=False, verbose_name='Aceptó recibir novedades')),
                ('fecha_consentimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del consentimiento')),
                ('consentimiento_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del consentimiento')),
                ('consentimiento_texto', models.TextField(blank=True, verbose_name='Texto aceptado')),
                ('baja', models.BooleanField(default=False, verbose_name='Se dio de baja')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('token_baja', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actividad')),
            ],
            options={
                'verbose_name': 'Interesado',
                'verbose_name_plural': 'Interesados',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_visita', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='VisitaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces', models.PositiveIntegerField(default=1)),
                ('primera', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visita a propiedad',
                'verbose_name_plural': 'Visitas a propiedades',
            },
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='domicilio_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domicilio legal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='email_privacidad',
            field=models.EmailField(blank=True, help_text='Donde las personas piden ver, corregir o borrar sus datos. Si lo dejás vacío se usa info@davidrodriguezprop.com.', max_length=254, verbose_name='Email para consultas de privacidad'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, verbose_name='Razón social'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Guardada el')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad guardada',
                'verbose_name_plural': 'Propiedades guardadas',
            },
        ),
        migrations.AddConstraint(
            model_name='interesado',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='interesado_email_unico'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='propiedades.interesado'),
        ),
        migrations.AddField(
            model_name='alertabusqueda',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='propiedades.interesado'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='interesado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes', to='propiedades.interesado'),
        ),
        migrations.AddField(
            model_name='visitapropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='visitapropiedad',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='propiedades.visitante'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('interesado', 'propiedad'), name='favorito_unico'),
        ),
        migrations.AddConstraint(
            model_name='visitapropiedad',
            constraint=models.UniqueConstraint(fields=('visitante', 'propiedad'), name='visita_unica_por_propiedad'),
        ),
    ]
