# Generated by Django 5.2.17 on 2026-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_interesados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
