# Generated by Django 5.2.17 on 2026-09-21 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0013_destacada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(help_text='Ej: Corredor inmobiliario, Martillero público.', max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/', verbose_name='Foto')),
                ('whatsapp', models.CharField(blank=True, help_text='Con código de país, sin + ni espacios. Ej: 5491133405963', max_length=30, verbose_name='WhatsApp (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar en la web')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Los números más chicos aparecen primero.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de la propiedad')),
                ('tipo_propiedad', models.CharField(choices=[('Casa', 'Casa'), ('Depto', 'Departamento'), ('Local', 'Local Comercial'), ('Terreno', 'Terreno')], default='Casa', max_length=50, verbose_name='Tipo')),
                ('objetivo', models.CharField(choices=[('vender', 'Quiero venderla'), ('alquilar', 'Quiero alquilarla'), ('saber', 'Solo quiero saber cuánto vale')], default='saber', max_length=20, verbose_name='Qué quiere hacer')),
                ('metros_cubiertos', models.PositiveIntegerField(blank=True, null=True, verbose_name='M² cubiertos')),
                ('dormitorios', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dormitorios')),
                ('mensaje', models.TextField(blank=True, verbose_name='Comentarios')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
            ],
            options={
                'verbose_name': 'Solicitud de tasación',
                'verbose_name_plural': 'Solicitudes de tasación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('zona', models.CharField(blank=True, help_text='Ej: Castelar. Es opcional.', max_length=100, verbose_name='Barrio o localidad')),
                ('texto', models.TextField(help_text='Lo que dijo el cliente, con sus palabras y con su permiso.', verbose_name='Testimonio')),
                ('estrellas', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrellas (1 a 5)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/', verbose_name='Foto (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar en la web')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Los números más chicos aparecen primero.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='origen',
            field=models.CharField(choices=[('favorito', 'Guardó una propiedad'), ('alerta', 'Pidió alertas de búsqueda'), ('popup', 'Ventana de novedades'), ('consulta', 'Consulta por una propiedad'), ('contacto', 'Formulario de contacto'), ('tasacion', 'Pidió una tasación')], default='popup', max_length=20, verbose_name='Cómo llegó'),
        ),
    ]
