# Generated by Django 5.2.17 on 2026-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0014_tasacion_testimonios_equipo_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtasacion',
            name='objetivo',
            field=models.CharField(choices=[('vender', 'Quiero venderla'), ('alquilar', 'Quiero alquilarla'), ('saber', 'Solo quiero saber su precio')], default='saber', max_length=20, verbose_name='Qué quiere hacer'),
        ),
    ]
